import { Poppins } from "next/font/google";
import "./globals.css";
import Nav from "./ui/navigation/Nav";

const poppins = Poppins({
  variable: "--font-poppins-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`  ${poppins.className}    antialiased`}>
        <div className="flex w-full h-screen  ">
          <div className="w-[380px] shrink-0">
            <Nav />
          </div>
          <div className="w-full ">{children}</div>
        </div>
      </body>
    </html>
  );
}
